### PR TITLE
Fix batch size seed

### LINKED ISSUE #29: Create ibmdb2__get_batch_size and return less than 10000
Having trouble running large seeds on our DB2 cluster. If reducing batch_size to 200 or 1000 it seems to work. Maybe the default should be something like that. Suggestions?

```
{% macro ibmdb2__get_batch_size() %}
  {{ return(1000) }}
{% endmacro %}
```

### PR DESCRIPTION
**Pull request by mikaeltw**
Make the macro `get_batch_size` adjustable by specifying:

```
vars:
    ibmdb2_batch_size: BATCH_SIZE
```
in `dbt_project.yml`.

closes #29

### CODE REVIEW

**Comment by mikaeltw** [comment]
@aurany , was it something along these lines you had in mind?

**Comment by mikaeltw** [comment]
`ImportError: cannot import name 'Mapping' from 'collections'` is thrown at runtime when installing with the current `poetry.lock`, resolved by making a new one. This is probably related to the `requests` package. It is also hinted by this warning that is thrown:
```
RequestsDependencyWarning: urllib3 (1.26.5) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
```

this is unrelated to the edits in this PR, and is probably due to `poetry` not locking version tight enough and dependency packages that have had releases since the last merge.

**Comment by mikaeltw** [comment]
Thanks! Yeah, I thought about that but I do not know how to test/make sure the `dbt seed` uses the macro, so leaving only testing for the macro is perhaps good enough as you say.

File: dbt/include/ibmdb2/macros/materializations/seeds/helpers.sql [hunk 1]
```diff
@@ -0,0 +1,3 @@
+{% macro ibmdb2__get_batch_size() %}
+  {{ return(var('ibmdb2_batch_size', 1000)) }}
```
Comment (aurany) [inline dbt/include/ibmdb2/macros/materializations/seeds/helpers.sql:2]: 1000 is a good starting point i believe

File: tests/functional/adapter/test_seeding.py [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+
+    @pytest.fixture(scope="class")
+    def batch_size_test(self):
+        return {
+            "test_batch_size.sql": test_batch_size_sql,
+        }
+
+    @pytest.mark.parametrize("custom,BATCH_SIZE", [(True, 200), (False, 1000)])
+    def test_get_batch_size_macro(self, project, batch_size_test, custom, BATCH_SIZE):
+        results = run_dbt(["seed"])
```
Comment (aurany) [inline tests/functional/adapter/test_seeding.py:48]: `dbt seed` does not support --vars and it will not use the custom batch sizes

**Review by aurany — APPROVED** [review]

File: tests/functional/adapter/test_seeding.py (hunk 2 above)
Comment (mikaeltw) [reply tests/functional/adapter/test_seeding.py:48]: Ah sorry, that is true. But it will on the other hand respect `vars:` in a `dbt_project.yml` file. Maybe we can follow up with setting up a class that uses a defualt project and test `dbt seed` with that? Or that class is perhaps already defined?
